const results: Job[] = [
  {
    key: 'infatec',
    name: 'Infatec - Soluções Tecnológicas',
    logo_dark: '/images/experiences/logo_dark_infatec.png',
    logo_light: '/images/experiences/logo_light_infatec.png',
    url: 'https://www.infatec.com.br/',
    tags: ['PHP', 'MySQL', 'Laravel'],
    date_start: '',
    date_end: '',
  },
  {
    key: 'w16',
    name: 'W16 - Software House',
    logo_dark: '/images/experiences/logo-w16.jpg',
    logo_light: '/images/experiences/logo-w16.jpg',
    url: 'https://w16.dev/',
    tags: ['Nexjs', 'NestJS', 'Tailwind CSS', 'React.js'],
    date_start: '',
    date_end: '',
  },
  {
    key: 'maida',
    name: 'Controle de Vendas',
    logo_dark: '/images/experiences/logo-dark-maida.svg',
    logo_light: '/images/experiences/logo-light-maida.svg',
    url: 'https://web.rokkos.app',
    tags: ['React.js', 'NodeJs', 'react-admin', 'Sass'],
    date_start: '',
    date_end: '',
  },
  {
    key: 'ana-paula-carvalho',
    name: 'Ana Paula Carvalho',
    logo_dark: '/images/results/logo-ana-paula-Photoroom.png',
    logo_light: '/images/experiences/logo-dark-ana-paula-Photoroom.png',
    url: 'https://www.anapaulacarvalho.com/',
    tags: ['Nexjs', 'Tailwind CSS', 'React.js'],
    date_start: '',
    date_end: '',
  },
  {
    key: 'frellancer',
    name: 'Mauboa Freelancer',
    logo_dark: '/images/experiences/logo-dark-mauboa.png',
    logo_light: '/images/experiences/logo-light-mauboa.png',
    url: 'https://www.anapaulacarvalho.com/',
    tags: ['Nexjs', 'Tailwind CSS', 'React.js'],
    date_start: '',
    date_end: '',
  },
];

export default results;
